# =========================================
# 🎮 PokéArena Frontend - Render Deploy Config
# =========================================
#
# Este arquivo configura automaticamente o deploy do frontend React + Vite
# na Render como um Static Site (arquivos estáticos servidos via CDN).
#
# Como usar:
#   1. Faça commit deste arquivo: git add render.yaml && git commit -m "Add Render config"
#   2. Push para o GitHub: git push origin main
#   3. Na Render: Dashboard → New → Blueprint → Conectar repositório
#   4. Render detecta o render.yaml automaticamente e cria tudo com um clique!
#
# Documentação: https://render.com/docs/static-sites
# =========================================

services:
  # =========================================
  # 🌐 Static Site (Frontend SPA)
  # =========================================
  - type: web
    name: poke-arena-front
    env: static  # Static Site - serve apenas arquivos estáticos via CDN global
    region: oregon  # us-west (mais barato) - alternativas: ohio (us-east), frankfurt (eu-central)

    # Branch principal para auto-deploy
    branch: main

    # =========================================
    # 🔨 Build Configuration
    # =========================================

    # Build Command: instala dependências e compila o projeto
    # npm ci: instalação limpa e determinística (mais confiável que npm install)
    # npm run build: executa "tsc -b && vite build" do package.json
    buildCommand: npm ci && npm run build

    # Publish Directory: pasta onde ficam os arquivos buildados
    # O Vite gera os arquivos compilados na pasta "dist/"
    publishDir: dist

    # Auto-deploy: deploy automático quando há push na branch principal
    autoDeploy: true

    # =========================================
    # 🔧 Variáveis de Ambiente
    # =========================================
    # IMPORTANTE: Variáveis do Vite DEVEM começar com "VITE_"
    # Elas são injetadas em BUILD TIME (não runtime)

    envVars:
      # URL da API Backend (conecta ao serviço poke-arena-back)
      - key: VITE_API_URL
        value: https://poke-arena-back.onrender.com

      # Nome da aplicação (usado no código via import.meta.env.VITE_APP_NAME)
      - key: VITE_APP_NAME
        value: PokéArena

      # Versão da aplicação
      - key: VITE_APP_VERSION
        value: 1.0.0

      # Node.js version para o processo de build
      - key: NODE_VERSION
        value: 20

    # =========================================
    # 🛣️ Routes - SPA Routing Support
    # =========================================
    # Como o projeto usa React Router, precisamos garantir que
    # TODAS as rotas (ex: /battle, /pokemon/123) sejam tratadas
    # pelo React Router e não pelo servidor.
    #
    # Sem essa configuração:
    #   ❌ /battle → 404 Not Found (servidor procura arquivo battle.html)
    #
    # Com essa configuração:
    #   ✅ /battle → index.html → React Router carrega a rota

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    # =========================================
    # 🔒 Headers - Segurança e Performance
    # =========================================

    headers:
      # ---------------------------------------
      # Segurança
      # ---------------------------------------

      # X-Frame-Options: previne clickjacking
      # DENY: não permite que o site seja embedado em iframes
      - path: /*
        name: X-Frame-Options
        value: DENY

      # X-Content-Type-Options: previne MIME sniffing
      # nosniff: força o browser a respeitar o Content-Type declarado
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

      # X-XSS-Protection: proteção adicional contra XSS
      # 1; mode=block: ativa proteção e bloqueia páginas suspeitas
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block

      # Referrer-Policy: controla informações de referrer
      # strict-origin-when-cross-origin: envia referrer apenas para HTTPS
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin

      # Permissions-Policy: desabilita recursos desnecessários
      # Camera, microphone, geolocation desabilitados por padrão
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()

      # ---------------------------------------
      # Performance e Cache
      # ---------------------------------------

      # Cache agressivo para assets estáticos (JS, CSS, images)
      # Os assets do Vite incluem hash no nome (ex: main.abc123.js)
      # Isso significa que são immutable - podem ser cacheados forever
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

      # Cache para index.html (sempre revalidar para pegar novas versões)
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate

      # Compressão gzip/brotli (Render faz automaticamente, mas é bom explicitar)
      - path: /*
        name: Content-Encoding
        value: gzip

# =========================================
# 📝 Notas Importantes
# =========================================
#
# 1. STATIC SITE vs WEB SERVICE:
#    - Static Site: arquivos estáticos servidos via CDN (seu caso)
#    - Web Service: aplicações Node.js/SSR (Next.js, Express, etc)
#    - Static Site é GRATUITO na Render (até 100GB bandwidth/mês)
#
# 2. VARIÁVEIS VITE (Build Time):
#    - Variáveis VITE_* são injetadas durante o BUILD
#    - Não podem ser mudadas depois do build (diferente de runtime vars)
#    - Se mudar VITE_API_URL, precisa fazer novo deploy (rebuild)
#    - Acesse no código: import.meta.env.VITE_API_URL
#
# 3. CORS NO BACKEND:
#    - O backend DEVE permitir requisições do frontend
#    - Adicione no main.ts do NestJS:
#      app.enableCors({
#        origin: [
#          'http://localhost:5173', // dev local
#          'https://poke-arena-front.onrender.com', // produção
#        ],
#        credentials: true,
#      });
#
# 4. SPA ROUTING:
#    - A regra "/* → /index.html" garante que o React Router funcione
#    - Sem ela: acessar /battle diretamente → 404
#    - Com ela: acessar /battle → index.html → React Router carrega a rota
#
# 5. CUSTOM DOMAIN:
#    - Por padrão: poke-arena-front.onrender.com
#    - Para domínio próprio: Dashboard → Settings → Custom Domain
#    - Adicione um CNAME record no seu DNS apontando para Render
#
# 6. HTTPS/SSL:
#    - Render fornece HTTPS automático e gratuito
#    - Certificado Let's Encrypt renovado automaticamente
#    - Nenhuma configuração necessária
#
# 7. BUILD FAILURES (troubleshooting):
#    - Erro "command not found": verifique buildCommand
#    - Erro "cannot find module": verifique se está usando "npm ci"
#    - Build muito lento: considere usar pnpm ao invés de npm
#    - Erro de TypeScript: rode "npm run build" localmente primeiro
#
# 8. PERFORMANCE:
#    - CDN global: baixa latência mundial
#    - Assets com hash: cache infinito seguro
#    - Brotli compression: ~20% menor que gzip
#    - Static Site é extremamente rápido (sem processamento server-side)
#
# 9. CUSTO:
#    - Static Sites: GRATUITO na Render
#    - Bandwidth: 100GB/mês incluído
#    - Sem limites de build minutes
#    - Deploy ilimitado
#
# 10. DEPLOY FLOW:
#     1. git push origin main
#        ↓
#     2. Render detecta mudança
#        ↓
#     3. Build:
#        - npm ci (instala deps)
#        - npm run build (compila TS + Vite)
#        - gera pasta dist/
#        ↓
#     4. Deploy:
#        - publica arquivos de dist/ no CDN
#        - aplica routes e headers
#        ↓
#     5. Live! 🎉
#        - https://poke-arena-front.onrender.com
#
# =========================================
# 🔗 URLs Importantes
# =========================================
#
# Frontend (após deploy):
#   https://poke-arena-front.onrender.com
#
# Backend (já configurado):
#   https://poke-arena-back.onrender.com
#
# Documentação Render:
#   - Static Sites: https://render.com/docs/static-sites
#   - Blueprint Spec: https://render.com/docs/blueprint-spec
#   - Deploy Hooks: https://render.com/docs/deploy-hooks
#
# =========================================
