# =========================================
# 🎮 PokéArena Frontend - Render Deploy Config
# =========================================
# Documentação: https://render.com/docs/static-sites
# =========================================

services:
  # =========================================
  # 🌐 Static Site (Frontend SPA)
  # =========================================
  - type: web
    name: poke-arena
    env: static  # Static Site - serve apenas arquivos estáticos via CDN global

    # Branch principal para auto-deploy
    branch: main

    # =========================================
    # 🔨 Build Configuration
    # =========================================

    # Build Command: instala dependências e compila o projeto
    buildCommand: npm ci && npm run build

    # Publish Directory: pasta onde ficam os arquivos buildados
    # O Vite gera os arquivos compilados na pasta "dist/"
    staticPublishPath: dist

    # Auto-deploy: deploy automático quando há push na branch principal
    autoDeploy: true

    # =========================================
    # 🔧 Variáveis de Ambiente
    # =========================================

    envVars:
      # URL da API Backend (conecta ao serviço poke-arena-back)
      - key: VITE_API_URL
        value: https://poke-arena-back.onrender.com

      # Nome da aplicação (usado no código via import.meta.env.VITE_APP_NAME)
      - key: VITE_APP_NAME
        value: PokéArena

      # Versão da aplicação
      - key: VITE_APP_VERSION
        value: 1.0.0

      # Node.js version para o processo de build
      - key: NODE_VERSION
        value: 20
# =========================================
# Documentação Render:
#   - Static Sites: https://render.com/docs/static-sites
#   - Blueprint Spec: https://render.com/docs/blueprint-spec
#   - Deploy Hooks: https://render.com/docs/deploy-hooks
#
# =========================================
